### ISSUE TITLE
1月23号的提交有问题，导致一直在广告页面出不去

### ISSUE THREAD

**Issue by little-wheat** [gofreeing/qidian-hamibot#1]
建议直接等待17秒以上算了，不用搞那么复杂获取时间，或者搞个超时时间

**Comment by little-wheat** [comment]
好像和时间没关系，非游戏类的广告出不去

**Comment by gofreeing** [comment]
最新提交观看完视频没测，其他的自己用的基本没问题，你可以自己去测

**Comment by gofreeing** [comment]
> 好像和时间没关系，非游戏类的广告出不去

最新提交观看完视频没测，其他的自己用的基本没问题，你可以自己去测

**Comment by little-wheat** [comment]
> > 好像和时间没关系，非游戏类的广告出不去
> 
> 最新提交观看完视频没测，其他的自己用的基本没问题，你可以自己去测

ok了，最新提交没问题了
